steps:
  - name: ubuntu:18.04
    args:
      - '-c'
      - |
        set -x
        ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime
        ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo "Europe/London" > /etc/timezone
        DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq tzdata sudo lsb-core lsb-release apt-utils #  > /dev/null
        source scripts/cloud_build_test_debian_ubuntu.sh
        mv clouddq-executable.zip debian11_python3.9.7_clouddq-executable.zip
        mv clouddq-executable.zip.hashsum debian11_python3.9.7_clouddq-executable.zip.hashsum
    entrypoint: /bin/bash
    env:
    - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
    - 'CLOUDDQ_BIGQUERY_DATASET=${_CLOUDDQ_BIGQUERY_DATASET}'
    - 'CLOUDDQ_BIGQUERY_REGION=${_CLOUDDQ_BIGQUERY_REGION}'
    - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
    - 'GCS_BAZEL_CACHE=${_GCS_BAZEL_CACHE}'
    - 'DATAPLEX_LAKE_NAME=${_DATAPLEX_LAKE_NAME}'
    - 'DATAPLEX_REGION_ID=${_DATAPLEX_REGION_ID}'
    - 'DATAPLEX_ENDPOINT=${_DATAPLEX_ENDPOINT}'
    - 'DATAPLEX_TARGET_BQ_DATASET=${_DATAPLEX_TARGET_BQ_DATASET}'
    - 'DATAPLEX_TARGET_BQ_TABLE=${_DATAPLEX_TARGET_BQ_TABLE}'
    - 'DATAPLEX_TASK_SA=${_DATAPLEX_TASK_SA}'
  - name: debian:11-slim
    args:
      - '-c'
      - |
        set -x
        DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq tzdata sudo lsb-release apt-utils
        source scripts/cloud_build_test_debian_ubuntu.sh
        make test test_dataplex_task
        mv clouddq-executable.zip debian11_python3.9.7_clouddq-executable.zip
        mv clouddq-executable.zip.hashsum debian11_python3.9.7_clouddq-executable.zip.hashsum
    entrypoint: /bin/bash
    env:
    - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
    - 'CLOUDDQ_BIGQUERY_DATASET=${_CLOUDDQ_BIGQUERY_DATASET}'
    - 'CLOUDDQ_BIGQUERY_REGION=${_CLOUDDQ_BIGQUERY_REGION}'
    - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
    - 'GCS_BAZEL_CACHE=${_GCS_BAZEL_CACHE}'
    - 'DATAPLEX_LAKE_NAME=${_DATAPLEX_LAKE_NAME}'
    - 'DATAPLEX_REGION_ID=${_DATAPLEX_REGION_ID}'
    - 'DATAPLEX_ENDPOINT=${_DATAPLEX_ENDPOINT}'
    - 'DATAPLEX_TARGET_BQ_DATASET=${_DATAPLEX_TARGET_BQ_DATASET}'
    - 'DATAPLEX_TARGET_BQ_TABLE=${_DATAPLEX_TARGET_BQ_TABLE}'
    - 'DATAPLEX_TASK_SA=${_DATAPLEX_TASK_SA}'
timeout: 3600s
options:
  machineType: 'E2_HIGHCPU_8'
logsBucket: 'gs://dataplex-clouddq-github-cloud-build'
artifacts:
  objects:
    location: 'gs://dataplex-clouddq-api-integration/build-artifacts/'
    paths: ['debian11_python3.9.7_clouddq-executable.zip', 'debian11_python3.9.7_clouddq-executable.zip.hashsum']