steps:
  - name: ubuntu:18.04
    args:
      - '-c'
      - |
        DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y tzdata sudo  > /dev/null
        source scripts/cloud_build_ubuntu18.sh
        source scripts/install_gcloud.sh
        gsutil cp clouddq_patched.zip gs://$_GCS_BUCKET_NAME/build-artifacts/ubuntu18.04/python3.8.6/`date -I`/`date -Iseconds`_${SHORT_SHA}/clouddq-executable.zip
        gsutil cp clouddq_patched.zip.hashsum gs://$_GCS_BUCKET_NAME/build-artifacts/ubuntu18.04/python3.8.6/`date -I`/`date -Iseconds`_${SHORT_SHA}/clouddq-executable.zip.hashsum
    entrypoint: /bin/bash
    env:
    - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
    - 'CLOUDDQ_BIGQUERY_DATASET=${_CLOUDDQ_BIGQUERY_DATASET}'
    - 'CLOUDDQ_BIGQUERY_REGION=${_CLOUDDQ_BIGQUERY_REGION}'
    - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
    - 'GCS_BAZEL_CACHE=${_GCS_BAZEL_CACHE}'
    - 'DATAPLEX_LAKE_NAME=${_DATAPLEX_LAKE_NAME}'
    - 'DATAPLEX_REGION_ID=${_DATAPLEX_REGION_ID}'
    - 'DATAPLEX_ENDPOINT=${_DATAPLEX_ENDPOINT}'
    - 'DATAPLEX_TARGET_BQ_DATASET=${_DATAPLEX_TARGET_BQ_DATASET}'
    - 'DATAPLEX_TARGET_BQ_TABLE=${_DATAPLEX_TARGET_BQ_TABLE}'
    - 'DATAPLEX_TASK_SA=${_DATAPLEX_TASK_SA}'
  - name: debian:11-slim
    args:
      - '-c'
      - |
        DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y tzdata sudo  > /dev/null
        source scripts/cloud_build_debian11.sh
        source scripts/install_gcloud.sh
        gsutil cp clouddq_patched.zip gs://$_GCS_BUCKET_NAME/build-artifacts/debian11/python3.9.2/`date -I`/`date -Iseconds`_${SHORT_SHA}/clouddq-executable.zip
        gsutil cp clouddq_patched.zip.hashsum gs://$_GCS_BUCKET_NAME/build-artifacts/debian11/python3.9.2/`date -I`/`date -Iseconds`_${SHORT_SHA}/clouddq-executable.zip.hashsum
    entrypoint: /bin/bash
    env:
    - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
    - 'CLOUDDQ_BIGQUERY_DATASET=${_CLOUDDQ_BIGQUERY_DATASET}'
    - 'CLOUDDQ_BIGQUERY_REGION=${_CLOUDDQ_BIGQUERY_REGION}'
    - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
    - 'GCS_BAZEL_CACHE=${_GCS_BAZEL_CACHE}'
    - 'DATAPLEX_LAKE_NAME=${_DATAPLEX_LAKE_NAME}'
    - 'DATAPLEX_REGION_ID=${_DATAPLEX_REGION_ID}'
    - 'DATAPLEX_ENDPOINT=${_DATAPLEX_ENDPOINT}'
    - 'DATAPLEX_TARGET_BQ_DATASET=${_DATAPLEX_TARGET_BQ_DATASET}'
    - 'DATAPLEX_TARGET_BQ_TABLE=${_DATAPLEX_TARGET_BQ_TABLE}'
    - 'DATAPLEX_TASK_SA=${_DATAPLEX_TASK_SA}'
timeout: 3600s