steps:
  - name: debian:11-slim
    args:
      - '-c'
      - |
        set -x
        DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq tzdata sudo lsb-release apt-utils
        source scripts/cloud_build_test_debian_ubuntu.sh "3.9.7"
        make test test_dataplex_task
        make check
        source scripts/install_gcloud.sh
        gsutil ls gs://$_GCS_BUCKET_NAME
        gsutil cp clouddq_patched.zip gs://${_GCS_BUCKET_NAME}/build-artifacts/debian11/python3.9/`date -I`/${SHORT_SHA}_${BRANCH_NAME}/clouddq-executable.zip
        gsutil cp clouddq_patched.zip.hashsum gs://${_GCS_BUCKET_NAME}/build-artifacts/debian11/python3.9/`date -I`/${SHORT_SHA}_${BRANCH_NAME}/clouddq-executable.zip.hashsum
    entrypoint: /bin/bash
    env:
    - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}'
    - 'CLOUDDQ_BIGQUERY_DATASET=${_CLOUDDQ_BIGQUERY_DATASET}'
    - 'CLOUDDQ_BIGQUERY_REGION=${_CLOUDDQ_BIGQUERY_REGION}'
    - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
    - 'GCS_BAZEL_CACHE=${_GCS_BAZEL_CACHE}'
    - 'DATAPLEX_LAKE_NAME=${_DATAPLEX_LAKE_NAME}'
    - 'DATAPLEX_REGION_ID=${_DATAPLEX_REGION_ID}'
    - 'DATAPLEX_ENDPOINT=${_DATAPLEX_ENDPOINT}'
    - 'DATAPLEX_TARGET_BQ_DATASET=${_DATAPLEX_TARGET_BQ_DATASET}'
    - 'DATAPLEX_TARGET_BQ_TABLE=${_DATAPLEX_TARGET_BQ_TABLE}'
    - 'DATAPLEX_TASK_SA=${_DATAPLEX_TASK_SA}'
timeout: 3600s
options:
  machineType: 'E2_HIGHCPU_8'
logsBucket: 'gs://dataplex-clouddq-github-cloud-build'