# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: build-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-18.04, debian-11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: check addlicense
        run: make addlicense

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get gcloud CLI info
        run: gcloud info

      - name: test pip install
        run: |
          export GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
          export CLOUDDQ_BIGQUERY_DATASET="dq_test"
          export CLOUDDQ_BIGQUERY_REGION="EU"
          export GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
          export IMPERSONATION_SERVICE_ACCOUNT=${{ secrets.IMPERSONATION_SERVICE_ACCOUNT }}
          gcloud config set project "${GOOGLE_CLOUD_PROJECT}"
          sed -i s/\<your_gcp_project_id\>/${GOOGLE_CLOUD_PROJECT}/g configs/entities/test-data.yml
          make test-pip-install
        shell: bash

      - name: Use GCS Bazel Cache
        run: |
          echo "common --remote_cache=https://storage.googleapis.com/${{ secrets.BAZEL_CACHE_BUCKET }}" >> .bazelrc
          echo "common --google_default_credentials" >> .bazelrc
        shell: bash

      - name: install sandboxfs
        run: |
          sudo apt-get install libfuse-dev pkg-config -y
          wget https://github.com/bazelbuild/sandboxfs/releases/download/sandboxfs-0.2.0/sandboxfs-0.2.0-20200420-linux-x86_64.tgz
          sudo tar xzv -C /usr/local -f sandboxfs-0.2.0-20200420-linux-x86_64.tgz
        shell: bash

      - name: Cache bazel
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: lint check
        run: make check
        shell: bash

      - name: tests
        run: |
          export GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
          export CLOUDDQ_BIGQUERY_DATASET="dq_test"
          export CLOUDDQ_BIGQUERY_REGION="EU"
          export GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
          export GOOGLE_SDK_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
          export IMPERSONATION_SERVICE_ACCOUNT=${{ secrets.IMPERSONATION_SERVICE_ACCOUNT }}
          gcloud config set project "${GOOGLE_CLOUD_PROJECT}"
          make test
        shell: bash

      - name: build
        run: make build
        shell: bash
